version: '3'
services:
  frontend:
    build: ./frontend
    container_name: menu_frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_NAME=student-restaurant-menus
      - CHOKIDAR_USERPOLLING=true
  backend:
    build: ./backend
    container_name: menu_backend
    ports:
      - 3001:3001